steps:
# Copy the website content to a GS bucket
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: Sync the website content
  args: ['gsutil', '-m', 'rsync', '-d', '-r', 'website/', 'gs://coffeetime-dev-cloudresume']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: Invalidate the content CDN
  args: ['gcloud', 'compute', 'url-maps', 'invalidate-cdn-cache', 'cloudresume-url-map', '--path', '/*', '--project', '$PROJECT_ID']